x=input('Digite Algo:')
print(x,'É do tipo numerico?', x.isalnum())
print(x,'É do tipo alfabetico?', x.isalpha())
print(x,'Possui apenas letras ou numeros?', x.isalnum())
print(x,'Está em Caixa Alta?',x.isupper())
print(x,'Está em Caixa Baixa?', x.islower())